# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nfn_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Contest Title')),
                ('category', models.CharField(choices=[('DES', 'Design'), ('DEV', 'Development'), ('BUS', 'Business'), ('ENG', 'Engineering'), ('MED', 'Media Production'), ('CRE', 'Creative Writing')], max_length=20, verbose_name='Contest Category')),
                ('description', models.CharField(max_length=50, verbose_name='Contest Description')),
                ('details', models.TextField(verbose_name='Contest Details')),
                ('image', models.ImageField(upload_to='uploads/contest_img/')),
                ('award', models.CharField(max_length=50, verbose_name='Contest Award')),
                ('is_approved', models.BooleanField(verbose_name='Approved')),
                ('is_ongoing', models.BooleanField(verbose_name='Ongoing')),
                ('date_started', models.DateField(verbose_name='Contest Start Date')),
                ('date_deadline', models.DateField(verbose_name='Contest Deadline')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfn_user.C_Owner')),
            ],
        ),
    ]
