# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfn_contests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='hex_code_2',
            field=models.CharField(default='#212121', max_length=7, verbose_name='Second Color Code (For Gradients)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='hex_code',
            field=models.CharField(default='#212121', max_length=7, verbose_name='Color Code'),
        ),
    ]
