# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfn_contests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='is_approved',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Not Approved', 'Not Approved')], max_length=10, verbose_name='Contest Approval'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='is_ongoing',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Finished', 'Finished')], max_length=10, verbose_name='Contest Status'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='owner',
            field=models.CharField(max_length=20, verbose_name='Contest Owner'),
        ),
    ]
