# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfn_contests', '0002_auto_20151213_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfn_user.C_Owner'),
        ),
    ]
