# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfn_contests', '0003_auto_20151213_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.CharField(max_length=20)),
                ('a_names', models.CharField(max_length=200, verbose_name='Applicant Name(s)')),
                ('a_details', models.TextField(verbose_name='Applicant Details')),
                ('s_details', models.TextField(verbose_name='Submission Details')),
                ('s_file', models.FileField(blank=True, null=True, upload_to='../media/submissions/')),
                ('date_posted', models.DateTimeField(auto_now_add=True, verbose_name='Submission Date')),
            ],
        ),
        migrations.AlterField(
            model_name='contest',
            name='award',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contest',
            name='category',
            field=models.CharField(choices=[('Design', 'Design'), ('Development', 'Development'), ('Business', 'Business'), ('Engineering', 'Engineering'), ('MediaProduction', 'Media Production'), ('CreativeWriting', 'Creative Writing')], max_length=20),
        ),
        migrations.AlterField(
            model_name='contest',
            name='date_deadline',
            field=models.DateField(verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='date_started',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contest',
            name='details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='../media/contests/'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='is_approved',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Not Approved', 'Not Approved')], max_length=10, verbose_name='Approval'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='is_ongoing',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Finished', 'Finished')], max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='submission',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfn_contests.Contest'),
        ),
    ]
