# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfn_contests', '0004_auto_20151213_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='feedback',
            field=models.TextField(blank=True, null=True, verbose_name="Contest Owner's Feedback"),
        ),
        migrations.AlterField(
            model_name='submission',
            name='applicant',
            field=models.CharField(max_length=20, verbose_name='Applicant Account'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='nfn_contests.Contest'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='s_file',
            field=models.FileField(blank=True, null=True, upload_to='../media/submissions/', verbose_name='Submission File'),
        ),
    ]
