# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfn_contests', '0005_auto_20151213_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfn_contests.Contest'),
        ),
    ]
