# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfn_contests', '0007_submission_is_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='category',
            field=models.CharField(choices=[('Design', 'Design'), ('Development', 'Development'), ('business', 'business'), ('Engineering', 'Engineering'), ('MediaProduction', 'Media Production'), ('CreativeWriting', 'Creative Writing')], max_length=20),
        ),
        migrations.AlterField(
            model_name='contest',
            name='is_approved',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Not Approved', 'Not Approved')], max_length=20, verbose_name='Approval'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='is_ongoing',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Finished', 'Finished')], max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='is_winner',
            field=models.BooleanField(default=False, verbose_name='Winner!'),
        ),
    ]
