# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfn_contests', '0008_auto_20151214_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='category',
            field=models.CharField(choices=[('design', 'Design'), ('development', 'Development'), ('business', 'Business'), ('engineering', 'Engineering'), ('mediaproduction', 'Media Production'), ('creativewriting', 'Creative Writing')], max_length=20),
        ),
        migrations.AlterField(
            model_name='contest',
            name='image',
            field=models.ImageField(null=True, upload_to='../media/contests/'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='s_file',
            field=models.FileField(null=True, upload_to='../media/submissions/', verbose_name='Submission File'),
        ),
    ]
