# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfn_contests', '0009_auto_20151215_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='category',
            field=models.CharField(choices=[('design', 'Design'), ('development', 'Development'), ('business', 'Business'), ('engineering', 'Engineering'), ('mediaproduction', 'Media Production'), ('creativewriting', 'Creative Writing')], max_length=30),
        ),
        migrations.AlterField(
            model_name='contest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='../media/contests/'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='is_ongoing',
            field=models.CharField(blank=True, choices=[('Ongoing', 'Ongoing'), ('Finished', 'Finished')], max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
