# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfn_contests', '0010_auto_20151216_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='Approved'),
        ),
    ]
