# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfn_contests', '0011_auto_20151216_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='is_ongoing',
        ),
    ]
