# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 10:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfn_contests', '0012_remove_contest_is_ongoing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='applicant',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='s_file',
            field=models.FileField(blank=True, null=True, upload_to='../media/submissions/', verbose_name='Submission File'),
        ),
    ]
