# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfn_contests', '0014_auto_20151217_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('hex_code', models.CharField(max_length=7, verbose_name='Color Code')),
            ],
        ),
        migrations.AlterField(
            model_name='contest',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfn_contests.Category'),
        ),
    ]
