# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfn_contests', '0018_auto_20151217_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
