# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfn_contests', '0020_auto_20151217_1717'),
        ('nfn_contests', '0016_auto_20151217_1829'),
    ]

    operations = [
    ]
